[project]
name = "StackHub"
description = "Bitcoin Superapp on Stacks"
authors = []
telemetry = true
cache_dir = "./.cache"

# [[project.requirements]]
# contract_id = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sbtc-token"
# Mainnet: SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token

[contracts.launchpad]
path = "contracts/launchpad.clar"
clarity_version = 2
epoch = 2.5

[contracts.marketplace]
path = "contracts/marketplace.clar"
clarity_version = 2
epoch = 2.5

[contracts.reputation]
path = "contracts/reputation.clar"
clarity_version = 2
epoch = 2.5

[contracts.stacks-hub-avatars]
path = "contracts/stacks-hub-avatars.clar"
clarity_version = 2
epoch = 2.5

[contracts.sip009-nft-trait]
path = "contracts/sip009-nft-trait.clar"
clarity_version = 2
epoch = 2.5

[contracts.sip010-ft-trait]
path = "contracts/sip010-ft-trait.clar"
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
